### ISSUE TITLE
Create a server and also deploy to Heroku

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#6]
Lets create a server, put it on `server` folder. This server should just be a barebone express app that will serve the compiled client. Then deploy it to Heroku so I can view it publicly. Do you know how to do it?

**Comment by JustinHsie** [comment]
I finally got it to work! Had to learn how to integrate express and react and messed up a few times, but here's the site:
https://immense-peak-26369.herokuapp.com/

I also did some research but is my file structure right? Because server and client are sibling folders, idk if the root package.json start script is good practice

**Comment by Exegetech** [comment]
It is definitely redundant. But lets leave it for now, this is just for making sure I can see it easily. 

In the future, instead of pushing to `master`, just create a branch, for example `myfeature-xy` and push that branch and make a PR to `master` so it can be reviewed.
