### ISSUE TITLE
Create "List" related layout

### ISSUE THREAD

**Issue by Exegetech** [JustinHsie/eats#9]
Create all list related layout:
- Creating new list
- List all lists
- View a list
- Editing a list

As usual, just fake all data. It is easier if you put all fake data in one folder.

**Comment by JustinHsie** [comment]
I added the layouts, sorry they're so ugly lol. And the buttons don't work so I added quick links at the bottom.
Since View and Edit List are so similar, I think I'm just gonna combine them together in the future ie viewing a list also lets you edit. And list all lists will be on the homepage...for now

Also, I made the list layouts commits to a new branch that was branched from the previous app-home branch (not master) because I wanted to work from the most recent version. Sorry if that's not the right way to do things, please let me know!
